use countries_api;
db.dropDatabase();
db.countries.insertMany([
     
    {
        "name": "United Kingdom",
        "officialName": "United Kingdom of Great Britain and Northern Ireland",
        "continent": "Europe",
        "capital": "London",
        "population": 67215293,
        "currency": {
                "officialName": "British pound",
                "symbol": "£",
                "name": "GBP"
                 },
        "areaKM": 242495,
        "highestPoint": "Ben Nevis",
        "highestPointMetres": 1343,
        "olympicMedalsTotal": 917,
        "goldMedals": 286, 
        "silverMedals": 316, 
        "bronzeMedals": 315,
        "about" : "The United Kingdom, made up of England, Scotland, Wales and Northern Ireland, is an island nation in northwestern Europe. England – birthplace of Shakespeare and The Beatles – is home to the capital, London, a globally influential centre of finance and culture.",
        "officialLanguage": "English",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/gb.svg",
        "borderingCountries": "Ireland",
        "nationalAnimal": "Lion",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Lion2010.jpg/800px-Lion2010.jpg",
        "googleMap": "https://goo.gl/maps/FoDtc3UKMkFsXAjHA",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Buckingham_Palace_aerial_view_2016_%28cropped%29.jpg/1920px-Buckingham_Palace_aerial_view_2016_%28cropped%29.jpg"
    }, 

    {
        "name": "France",
        "officialName": "French Republic",
        "continent": "Europe",
        "capital": "Paris",
        "population": 67391582,
        "currency": {
                "officialName": "Euro",
                "symbol": "€",
                "name": "Euro"
                 },
        "areaKM": 547660 ,
        "highestPoint": "Mont Blanc",
        "highestPointMetres": 4810,
        "olympicMedalsTotal": 761,
        "goldMedals": 225, 
        "silverMedals": 257, 
        "bronzeMedals": 279,
        "about" : "France, in Western Europe, encompasses medieval cities, alpine villages and Mediterranean beaches. Paris, its capital, is famed for its fashion houses, classical art museums including the Louvre and monuments like the Eiffel Tower. The country is also renowned for its wines and sophisticated cuisine.",
        "officialLanguage": "French",   
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/fr.svg",
        "borderingCountries": "Andorra, Belgium, Germany, Italy, Luxembourg, Monaco, Spain, Switzerland",
        "nationalAnimal": "The Gallic Rooster",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/3/35/Coq-gaulois-dore.JPG",
        "googleMap": "https://goo.gl/maps/g7QxxSFsWyTPKuzd7",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/800px-Tour_Eiffel_Wikimedia_Commons.jpg"
    },

    {
        "name": "Spain",
        "officialName": "Kingdom of Spain",
        "continent": "Europe",
        "capital": "Madrid",
        "population": 47351567,
        "currency": {
                "officialName": "Euro",
                "symbol": "€",
                "name": "Euro"
                 },
        "areaKM": 505992,
        "highestPoint": "Mulhacen",
        "highestPointMetres": 3479,
        "olympicMedalsTotal": 168,
        "goldMedals": 48, 
        "silverMedals": 78, 
        "bronzeMedals": 48,
        "about" : "Spain, a country on Europe’s Iberian Peninsula, includes 17 autonomous regions with diverse geography and cultures. Capital city Madrid is home to the Royal Palace and Prado museum, housing works by European masters.",
        "officialLanguage": "Spanish",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/es.svg",
        "borderingCountries": "Andorra, France, Gibraltar, Portugal, Morocco",
        "nationalAnimal": "Bull",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/San_marcos_bullfight_01.jpg/1920px-San_marcos_bullfight_01.jpg",
        "googleMap": "https://goo.gl/maps/138JaXW8EZzRVitY9",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Dawn_Charles_V_Palace_Alhambra_Granada_Andalusia_Spain.jpg/1920px-Dawn_Charles_V_Palace_Alhambra_Granada_Andalusia_Spain.jpg"
    },
    {
        "name": "Italy",
        "officialName": "Italian Republic",
        "continent": "Europe",
        "capital": "Rome",
        "population": 59554023,
        "currency": {
                "officialName": "Euro",
                "symbol": "€",
                "name": "Euro"
                 },
        "areaKM": 301336,
        "highestPoint": "Monte Bianco",
        "highestPointMetres": 4810,
        "olympicMedalsTotal": 618,
        "goldMedals": 217, 
        "silverMedals": 188, 
        "bronzeMedals": 213,
        "about" : "Italy, a European country with a long Mediterranean coastline, has left a powerful mark on Western culture and cuisine. Its capital, Rome, is home to the Vatican as well as landmark art and ancient ruins. Other major cities include Florence, with Renaissance masterpieces such as Michelangelo’s 'David' and Brunelleschi's Duomo; Venice, the city of canals; and Milan, Italy’s fashion capital.",
        "officialLanguage": "Italian",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/it.svg",
        "borderingCountries": "Austria, France, San Marino, Slovenia, Switzerland, Vatican City",
        "nationalAnimal": "Italian Wolf",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/9/93/Lupo_appenninico_3.jpg",
        "googleMap": "https://goo.gl/maps/8M1K27TDj7StTRTq8",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/The_Leaning_Tower_of_Pisa_SB.jpeg/800px-The_Leaning_Tower_of_Pisa_SB.jpeg"
    },
    {
        "name": "Germany",
        "officialName": "Federal Republic of Germany",
        "continent": "Europe",
        "capital": "Berlin",
        "population": 83240525,
        "currency": {
                "officialName": "Euro",
                "symbol": "€",
                "name": "Euro"
                 },
        "areaKM": 357114,
        "highestPoint": "The Zugspitze",
        "highestPointMetres": 2962,
        "olympicMedalsTotal": 653,
        "goldMedals": 201, 
        "silverMedals": 206, 
        "bronzeMedals": 246,
        "about" : "Germany is a Western European country with a landscape of forests, rivers, mountain ranges and North Sea beaches. It has over 2 millennia of history. Berlin, its capital, is home to art and nightlife scenes, the Brandenburg Gate and many sites relating to WWII. Munich is known for its Oktoberfest and beer halls, including the 16th-century Hofbräuhaus. Frankfurt, with its skyscrapers, houses the European Central Bank.",
        "officialLanguage": "German",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/de.svg",
        "borderingCountries": "Austria, Belgium, Czech Republic, Denmark, France, Luxembourg, Netherlands, Poland, Switzerland",
        "nationalAnimal": "Federal eagle",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Aquila_chrysaetos_Flickr.jpg/2560px-Aquila_chrysaetos_Flickr.jpg",
        "googleMap": "https://goo.gl/maps/mD9FBMq1nvXUBrkv6",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Brandenburger_Tor_abends.jpg"
    },
    {
        "name": "United States",
        "officialName": "United States of America",
        "continent": "North America",
        "capital": "Washington, D.C.",
        "population": 329484123,
        "currency": {
                "officialName": "United States Dollar",
                "symbol": "$",
                "name": "USD"
                 },
        "areaKM": 9372610,
        "highestPoint": "Denali",
        "highestPointMetres": 6190,
        "olympicMedalsTotal": 2632,
        "goldMedals": 1061, 
        "silverMedals": 832, 
        "bronzeMedals": 739,
        "about" : "The U.S. is a country of 50 states covering a vast swath of North America, with Alaska in the northwest and Hawaii extending the nation’s presence into the Pacific Ocean. Major Atlantic Coast cities are New York, a global finance and culture center, and capital Washington, DC. Midwestern metropolis Chicago is known for influential architecture and on the west coast, Los Angeles' Hollywood is famed for filmmaking.",
        "officialLanguage": "English",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/us.svg",
        "borderingCountries": "Canada, Mexico",
        "nationalAnimal": "Bald Eagle",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/e/e3/Haliaeetus_leucocephalus.jpeg",
        "googleMap": "https://goo.gl/maps/e8M246zY4BSjkjAv6",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/White_House_north_and_south_sides.jpg/1280px-White_House_north_and_south_sides.jpg"
    },
    {
        "name": "Mexico",
        "officialName": "United Mexican States",
        "continent": "North America",
        "capital": "Mexico City",
        "population": 128932753,
        "currency": {
                "officialName": "Mexican peso",
                "symbol": "$",
                "name": "MXN"
                 },
        "areaKM": 1964375,
        "highestPoint": "Pico de Orizaba",
        "highestPointMetres": 5675,
        "olympicMedalsTotal": 73,
        "goldMedals": 13, 
        "silverMedals": 24, 
        "bronzeMedals": 36,
        "about" : "Mexico, officially the United Mexican States, is a country in the southern portion of North America. It is bordered to the north by the United States; to the south and west by the Pacific Ocean; to the southeast by Guatemala, Belize, and the Caribbean Sea; and to the east by the Gulf of Mexico",
        "officialLanguage": "Spanish",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/mx.svg",
        "borderingCountries": "Belize, Guatemala, United States",
        "nationalAnimal": "Golden Eagle",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Golden_Eagle_in_flight_-_5.jpg/1284px-Golden_Eagle_in_flight_-_5.jpg",
        "googleMap": "https://goo.gl/maps/s5g7imNPMDEePxzbA",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Bellas_Artes_01.jpg/1920px-Bellas_Artes_01.jpg"
    },
    {
        "name": "Canada",
        "officialName": "Canada",
        "continent": "North America",
        "capital": "Ottawa",
        "population": 38005238,
        "currency": {
                "officialName": "Canadian Dollar",
                "symbol": "$",
                "name": "CAD"
                 },
        "areaKM": 9984670,
        "highestPoint": "Mount Logan",
        "highestPointMetres": 5959,
        "olympicMedalsTotal": 326,
        "goldMedals": 71, 
        "silverMedals": 108, 
        "bronzeMedals": 147,
        "about" : "Canada is a country in North America. Its ten provinces and three territories extend from the Atlantic to the Pacific and northward into the Arctic Ocean, covering 9.98 million square kilometres, making it the world's second-largest country by total area.",
        "officialLanguage": "French",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/ca.svg",
        "borderingCountries": "United States",
        "nationalAnimal": "North American beaver",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/6/6b/American_Beaver.jpg",
        "googleMap": "https://goo.gl/maps/jmEVLugreeqiZXxbA",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Toronto_-_ON_-_Toronto_Harbourfront7.jpg/800px-Toronto_-_ON_-_Toronto_Harbourfront7.jpg"
    },
    {
        "name": "Jamaica",
        "officialName": "Jamaica",
        "continent": "North America",
        "capital": "Kingston",
        "population": 2961161,
        "currency": {
                "officialName": "Jamaican dollar",
                "symbol": "$",
                "name": "Jamaican dollar"
                 },
        "areaKM": 10991,
        "highestPoint": "Blue Mountain Peak",
        "highestPointMetres": 2256,
        "olympicMedalsTotal": 87,
        "goldMedals": 26, 
        "silverMedals": 36, 
        "bronzeMedals": 25,
        "about" : "Jamaica, a Caribbean island nation, has a lush topography of mountains, rainforests and reef-lined beaches. Many of its all-inclusive resorts are clustered in Montego Bay, with its British-colonial architecture, and Negril, known for its diving and snorkeling sites. Jamaica is famed as the birthplace of reggae music, and its capital Kingston is home to the Bob Marley Museum, dedicated to the famous singer.",
        "officialLanguage": "English",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/jm.svg",
        "borderingCountries": "This country does not border any countries",
        "nationalAnimal": "Red-Billed streamertail",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Red-billed_Streamertail_2506104129.jpg/1599px-Red-billed_Streamertail_2506104129.jpg",
        "googleMap": "https://goo.gl/maps/Z8mQ6jxnRQKFwJy9A",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/8/81/56hoperd.JPG"
    },
    {
        "name": "Guatemala",
        "officialName": "Republic of Guatemala",
        "continent": " North America",
        "capital": "Guatemala City",
        "population": 16858333,
        "currency": {
                "officialName": "Guatemalan quetzal",
                "symbol": "Q",
                "name": "GTQ"
                 },
        "areaKM": 108889,
        "highestPoint": "Volcán Tajumulco",
        "highestPointMetres": 4220,
        "olympicMedalsTotal": 1,
        "goldMedals": 0, 
        "silverMedals": 1, 
        "bronzeMedals": 0,
        "about" : "Guatemala, a Central American country south of Mexico, is home to volcanoes, rainforests and ancient Mayan sites. The capital, Guatemala City, features the stately National Palace of Culture and the National Museum of Archaeology and Ethnology. Antigua, west of the capital, contains preserved Spanish colonial buildings. Lake Atitlán, formed in a massive volcanic crater, is surrounded by coffee fields and villages.",
        "officialLanguage": "Spanish",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/gt.svg",
        "borderingCountries": "Belize, El Salvador, Honduras, Mexico",
        "nationalAnimal": "Quetzal",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/7/70/Quetzal01.jpg",
        "googleMap": "https://goo.gl/maps/JoRAbem4Hxb9FYbVA",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Tikal_Temple1_2006_08_11.JPG/1024px-Tikal_Temple1_2006_08_11.JPG"
    },
    {
        "name": "Papua New Guinea",
        "officialName": "Independent State of Papua New Guinea",
        "continent": "Oceania",
        "capital": "Port Moresby",
        "population": 8947027,
        "currency": {
                "officialName": "Papua New Guinean kina",
                "symbol": "K",
                "name": "PGK"
                 },
        "areaKM": 462840,
        "highestPoint": "Mount Wilhelm",
        "highestPointMetres": 4509,
        "olympicMedalsTotal": 0,
        "goldMedals": 0, 
        "silverMedals": 0, 
        "bronzeMedals": 0,
        "about" : "Papua New Guinea, in the southwestern Pacific, encompasses the eastern half of New Guinea and its offshore islands. A country of immense cultural and biological diversity, it’s known for its beaches and coral reefs. Inland are active volcanoes, granite Mt. Wilhelm, dense rainforest and hiking routes like the Kokoda Trail. There are also traditional tribal villages, many with their own languages.",
        "officialLanguage": "English",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/pg.svg",
        "borderingCountries": "Indonesia",
        "nationalAnimal": "Dugong",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Dugong_Marsa_Alam.jpg/1600px-Dugong_Marsa_Alam.jpg",
        "googleMap": "https://goo.gl/maps/ChGmzZBjZ3vnBwR2A",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/2/2d/Mount_Wilhelm.jpg"
    },
    {
        "name": "New Zealand",
        "officialName": "New Zealand",
        "continent": "Oceania",
        "capital": "Wellington",
        "population": 5084300,
        "currency": {
                "officialName": "New Zealand dollar",
                "symbol": "$",
                "name": "NZD"
                 },
        "areaKM": 270467,
        "highestPoint": "Mt. Cook",
        "highestPointMetres": 3754,
        "olympicMedalsTotal": 137,
        "goldMedals": 53, 
        "silverMedals": 33, 
        "bronzeMedals": 51,
        "about" : "New Zealand is an island country in the southwestern Pacific Ocean. It consists of two main landmasses—the North Island and the South Island —and over 700 smaller islands.",
        "officialLanguage": "English",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/nz.svg",
        "borderingCountries": "This country does not border any countries",
        "nationalAnimal": "Kiwi",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/TeTuatahianui.jpg/900px-TeTuatahianui.jpg",
        "googleMap": "https://goo.gl/maps/xXiDQo65dwdpw9iu8",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Aoraki_Mount_Cook.JPG/1024px-Aoraki_Mount_Cook.JPG"
    },

    {
        "name": "Brazil",
        "officialName": "Federative Republic of Brazil",
        "continent": "South America",
        "capital": "Brasília",
        "population": 212559409,
        "currency": {
                "officialName": "Brazilian real",
                "symbol": "R$",
                "name": "BRL"
                 },
        "areaKM": 8515767,
        "highestPoint": "Pico da Neblina",
        "highestPointMetres": 2994,
        "olympicMedalsTotal": 150,
        "goldMedals": 37, 
        "silverMedals": 42, 
        "bronzeMedals": 71,
        "about" : "Brazil, officially the Federative Republic of Brazil, is the largest country in both South America and Latin America. At 8.5 million square kilometers and with over 211 million people, Brazil is the world's fifth-largest country by area and the sixth most populous.",
        "officialLanguage": "Portuguese",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/br.svg",
        "borderingCountries": "Argentina, Bolivia, Colombia, French Guiana, Guyana, Paraguay, Peru, Suriname, Uruguay, Venezuela",
        "nationalAnimal": "Rufous-bellied thrush",
        "animalPhoto": "",
        "googleMap": "https://goo.gl/maps/waCKk21HeeqFzkNC9",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Aerial_view_of_the_Statue_of_Christ_the_Redeemer.jpg"
    },
    
    {
        "name": "Argentina",
        "officialName": "Argentine Republic",
        "continent": "South America",
        "capital": "Buenos Aires",
        "population": 45376763,
        "currency": {
                "officialName": "Argentine peso",
                "symbol": "$",
                "name": "ARS"
                 },
        "areaKM": 2780400,
        "highestPoint": "Aconcagua",
        "highestPointMetres": 6959,
        "olympicMedalsTotal": 77,
        "goldMedals": 21, 
        "silverMedals": 26, 
        "bronzeMedals": 30,
        "about" : "Argentina, officially the Argentine Republic, is a country in the southern half of South America. Argentina covers an area of 2,780,400 km², making it the largest Spanish-speaking nation in the world by area.",
        "officialLanguage":"None (Spanish has de facto status)",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/ar.svg",
        "borderingCountries": "Bolivia, Brazil, Chile, Paraguay, Uruguay",
        "nationalAnimal": "	Rufous hornero",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Flickr_-_Dario_Sanches_-_JO%C3%83O-DE-BARRO_%28Furnarius_rufus%29_%283%29.jpg/300px-Flickr_-_Dario_Sanches_-_JO%C3%83O-DE-BARRO_%28Furnarius_rufus%29_%283%29.jpg",
        "googleMap": "https://goo.gl/maps/Z9DXNxhf2o93kvyc6",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Iguazu_National_Park_Falls.jpg/1920px-Iguazu_National_Park_Falls.jpg"
    },
    
    {
        "name": "Venezuela",
        "officialName": "Bolivarian Republic of Venezuela",
        "continent": "South America",
        "capital": "Caracas",
        "population": 28435943,
        "currency": {
                "officialName": "Venezuelan bolívar soberano",
                "symbol": "Bs.S.",
                "name": "VES"
                 },
        "areaKM": 916445,
        "highestPoint": "Bolívar Peak",
        "highestPointMetres": 4978,
        "olympicMedalsTotal": 19,
        "goldMedals": 3, 
        "silverMedals": 7, 
        "bronzeMedals": 9,
        "about" : "Venezuela is a country on the northern coast of South America with diverse natural attractions. Along its Caribbean coast are tropical resort islands including Isla de Margarita and the Los Roques archipelago. To the northwest are the Andes Mountains and the colonial town of Mérida, a base for visiting Sierra Nevada National Park.",
        "officialLanguage": "Spanish and Venezuelan Sign Language",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/ve.svg",
        "borderingCountries": "Brazil, Colombia, Guyana",
        "nationalAnimal": "Venezuelan troupial",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Curacao-Icterus-Icterus-2013.JPG/1591px-Curacao-Icterus-Icterus-2013.JPG",
        "googleMap": "https://goo.gl/maps/KLCwDN8sec7z2kse9",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/SaltoAngel4.jpg/1024px-SaltoAngel4.jpg"
    },
    {
        "name": "Suriname",
        "officialName": "Republic of Suriname",
        "continent": "South America",
        "capital": "Paramaribo",
        "population": 586634,
        "currency": {
                "officialName": "Surinamese dollar",
                "symbol": "$",
                "name": "SRD"
                 },
        "areaKM": 163820,
        "highestPoint": "Julianatop",
        "highestPointMetres": 1286,
        "olympicMedalsTotal": 2,
        "goldMedals": 1, 
        "silverMedals": 0, 
        "bronzeMedals": 1,
        "about" : "Suriname is a small country on the northeastern coast of South America. It's defined by vast swaths of tropical rainforest, Dutch colonial architecture and a melting-pot culture. ",
        "officialLanguage": "Dutch",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/sr.svg",
        "borderingCountries": "Brazil, French Guiana, Guyana",
        "nationalAnimal": "Lesser Kiskadee",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Lesser_kiskadee_%28Pitangus_lictor_panamense%29.jpg/440px-Lesser_kiskadee_%28Pitangus_lictor_panamense%29.jpg",
        "googleMap": "https://goo.gl/maps/iy7TuQLSi4qgoBoG7",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Leo_val_brownsberg.JPG/568px-Leo_val_brownsberg.JPG"
    },
    {
        "name": "Chile",
        "officialName": "Republic of Chile",
        "continent": "South America",
        "capital": "Santiago",
        "population": 19116209,
        "currency": {
                "officialName": "Chilean peso",
                "symbol": "$",
                "name": "CLP"
                 },
        "areaKM": 756102,
        "highestPoint": "Nevado Ojos del Salado",
        "highestPointMetres": 6891,
        "olympicMedalsTotal": 13,
        "goldMedals": 2, 
        "silverMedals": 7, 
        "bronzeMedals": 4,
        "about" : "Chile is a long, narrow country stretching along South America's western edge, with more than 6,000km of Pacific Ocean coastline. Santiago, its capital, sits in a valley surrounded by the Andes and Chilean Coast Range mountains.",
        "officialLanguage": "None (Spanish has de facto status)",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/cl.svg",
        "borderingCountries": "Argentina, Bolivia, Peru",
        "nationalAnimal": "Huemul",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Huemul_verdadero.JPG",
        "googleMap": "https://goo.gl/maps/XboxyNHh2fAjCPNn9",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Torres_del_Paine_y_cuernos_del_Paine%2C_montaje.jpg/1024px-Torres_del_Paine_y_cuernos_del_Paine%2C_montaje.jpg"
    },
    {
        "name": "Peru",
        "officialName": "Republic of Peru",
        "continent": "South America",
        "capital": "Lima",
        "population": 32971846,
        "currency": {
                "officialName": "Peruvian sol",
                "symbol": "S/ ",
                "name": "PEN"
                 },
        "areaKM": 1285216,
        "highestPoint": "Huascarán",
        "highestPointMetres": 6768,
        "olympicMedalsTotal": 4,
        "goldMedals": 1, 
        "silverMedals": 3, 
        "bronzeMedals": 0,
        "about" : "Peru is home to a section of Amazon rainforest and Machu Picchu, an ancient Incan city high in the Andes mountains. The region around Machu Picchu, including the Sacred Valley, Inca Trail and colonial city of Cusco, is rich in archaeological sites.",
        "officialLanguage": "Spanish, Aymara, Quechua",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/pe.svg",
        "borderingCountries": "Bolivia, Brazil, Chile, Colombia, Ecuador",
        "nationalAnimal": "Vicuña",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Vicunacrop.jpg",
        "googleMap": "https://goo.gl/maps/uDWEUaXNcZTng1fP6",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Machu_Picchu%2C_Peru.jpg"
    },
    {
        "name": "Uganda",
        "officialName": "Republic of Uganda",
        "continent": "Africa",
        "capital": "Kampala",
        "population": 45741000,
        "currency": {
                "officialName": "Ugandan shilling",
                "symbol": "Sh",
                "name": "UGX"
                 },
        "areaKM": 241550,
        "highestPoint": "Alexandra - Ruwenzori mountain range",
        "highestPointMetres": 5094,
        "olympicMedalsTotal": 11,
        "goldMedals": 4, 
        "silverMedals": 4, 
        "bronzeMedals": 3,
        "about" : "Uganda is a landlocked country in East Africa whose diverse landscape encompasses the snow-capped Rwenzori Mountains and immense Lake Victoria. Its abundant wildlife includes chimpanzees as well as rare birds.",
        "officialLanguage": "English, Swahili",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/ug.svg",
        "borderingCountries": "Democratic Republic of the Congo, Kenya, Rwanda, South Sudan, Tanzania",
        "nationalAnimal": "Grey crowned crane",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Balearica_regulorum_001.jpg/898px-Balearica_regulorum_001.jpg",
        "googleMap": "https://goo.gl/maps/Y7812hFiGa8LD9N68",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Murchison_Falls_-_by_Boschlech.jpg/1920px-Murchison_Falls_-_by_Boschlech.jpg"
    },
    {
        "name": "Algeria",
        "officialName": "People's Democratic Republic of Algeria",
        "continent": "Africa",
        "capital": "Algiers",
        "population": 510713,
        "currency": {
                "officialName": "Algerian dinar",
                "symbol": "د.ج",
                "name": "DZD"
                 },
        "areaKM": 2381741,
        "highestPoint": "Mount Tahat",
        "highestPointMetres": 3003,
        "olympicMedalsTotal": 17,
        "goldMedals": 5, 
        "silverMedals": 4, 
        "bronzeMedals": 8,
        "about" : "Algeria is a North African country with a Mediterranean coastline and a Saharan desert interior. Many empires have left legacies here, such as the ancient Roman ruins in seaside Tipaza.",
        "officialLanguage": "Arabic, Tamazight",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/dz.svg",
        "borderingCountries": "Tunisia , Libya, Niger, Western Sahara, Morocco, Mali and Mauritania",
        "nationalAnimal": "Fennec fox",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Fennec_Foxes.jpg",
        "googleMap": "https://goo.gl/maps/RsAyAfyaiNVb8DpW8",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Martyrs_Memorial._Algiers%2C_Algeria.jpg/1920px-Martyrs_Memorial._Algiers%2C_Algeria.jpg"
    },
    {
        "name": "Angola",
        "officialName": "Republic of Angola",
        "continent": "Africa",
        "capital": "Luanda",
        "population": 32866268,
        "currency": {
                "officialName": "Angolan kwanza",
                "symbol": "Kz",
                "name": "AOA"
                 },
        "areaKM": 1246700,
        "highestPoint": "Morro de Môco",
        "highestPointMetres": 2620,
        "olympicMedalsTotal": 0,
        "goldMedals": 0, 
        "silverMedals": 0, 
        "bronzeMedals": 0,
        "about" : "Angola is a Southern African nation whose varied terrain encompasses tropical Atlantic beaches, a labyrinthine system of rivers and Sub-Saharan desert that extends across the border into Namibia.",
        "officialLanguage": "Portuguese",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/ao.svg",
        "borderingCountries": "Republic of the Congo, Democratic Republic of the Congo, Zambia and Namibia",
        "nationalAnimal": "Red-crested turaco",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/RedcrestedTuraco.jpg/1500px-RedcrestedTuraco.jpg",
        "googleMap": "https://goo.gl/maps/q42Qbf1BmQL3fuZg9",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Moco.JPG/1920px-Moco.JPG"
    },
    {
        "name": "Egypt",
        "officialName": "Arab Republic of Egypt",
        "continent": "Africa",
        "capital": "Cairo",
        "population": 102334403,
        "currency": {
                "officialName": "Egyptian pound",
                "symbol": "£",
                "name": "EGP"
                 },
        "areaKM": 1002450,
        "highestPoint": "Mount Kātrīnā",
        "highestPointMetres": 2642,
        "olympicMedalsTotal": 38,
         "goldMedals": 8, 
        "silverMedals": 11, 
        "bronzeMedals": 19,
        "about" : "Egypt, a country linking northeast Africa with the Middle East, dates to the time of the pharaohs. Millennia-old monuments sit along the fertile Nile River Valley, including Giza's colossal Pyramids and Great Sphinx as well as Luxor's hieroglyph-lined Karnak Temple and Valley of the Kings tombs.",
        "officialLanguage": "Arabic",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/eg.svg",
        "borderingCountries": "Israel, Libya, Palestinian Territory, Sudan",
        "nationalAnimal": "Steppe Eagle ",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Steppe_Eagle_Portrait.jpg/1024px-Steppe_Eagle_Portrait.jpg",
        "googleMap": "https://goo.gl/maps/uoDRhXbsqjG6L7VG7",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/All_Gizah_Pyramids.jpg/1920px-All_Gizah_Pyramids.jpg"
    },
    {
        "name": "South Africa",
        "officialName": "Republic of South Africa",
        "continent": "Africa",
        "capital": "Pretoria, Bloemfontein, Cape Town",
        "population": 59308690,
        "currency": {
                "officialName": "South African rand",
                "symbol": "R",
                "name": "ZAR"
                 },
        "areaKM": 1221037,
        "highestPoint": "Thabana Ntlenyana",
        "highestPointMetres": 3482,
        "olympicMedalsTotal": 89,
        "goldMedals": 27, 
        "silverMedals": 33, 
        "bronzeMedals": 29,
        "about" : "South Africa is a country on the southernmost tip of the African continent, marked by several distinct ecosystems. Inland safari destination Kruger National Park is populated by big game. The Western Cape offers beaches, lush winelands around Stellenbosch and Paarl, craggy cliffs at the Cape of Good Hope, forest and lagoons along the Garden Route, and the city of Cape Town, beneath flat-topped Table Mountain.",
        "officialLanguage": "Afrikaans, English, Southern Ndebele, Sotho, Northern Sotho, Swazi, Tsonga, Tswana, Venda, Xhosa, Zulu",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/za.svg",
        "borderingCountries": "Botswana, Lesotho, Mozambique, Namibia, Eswatini and Zimbabwe",
        "nationalAnimal": "Springbok",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Springbok.JPG",
        "googleMap": "https://goo.gl/maps/CLCZ1R8Uz1KpYhRv6",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Ciudad_del_Cabo%2C_Kirstenbosch_NBG_33.jpg/2880px-Ciudad_del_Cabo%2C_Kirstenbosch_NBG_33.jpg"
    },
    {
        "name": "Morocco",
        "officialName": "Kingdom of Morocco",
        "continent": "Africa",
        "capital": "Rabat",
        "population": 36910558,
        "currency": {
                "officialName": "Moroccan dirham",
                "symbol": "د.م.",
                "name": "MAD"
                 },
        "areaKM": 446550,
        "highestPoint": "Mount Toubkal",
        "highestPointMetres": 4165,
        "olympicMedalsTotal": 24,
        "goldMedals": 7, 
        "silverMedals": 5, 
        "bronzeMedals": 12,
        "about" : "Morocco, a North African country bordering the Atlantic Ocean and Mediterranean Sea, is distinguished by its Berber, Arabian and European cultural influences. Marrakesh’s medina, a mazelike medieval quarter, offers entertainment in its Djemaa el-Fna square and souks (marketplaces) selling ceramics, jewelry and metal lanterns.",
        "officialLanguage": "Arabic, Tamazight",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/ma.svg",
        "borderingCountries": "Algeria, Western Sahara and Spain",
        "nationalAnimal": "Barbary lion",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/4/43/Barbary_lion.jpg",
        "googleMap": "https://goo.gl/maps/6oMv3dyBZg3iaXQ5A",
        "landmark": "https://upload.wikimedia.org/wikipedia/en/thumb/4/46/Hassan_II_Mosque.jpg/2560px-Hassan_II_Mosque.jpg"
    },
    {
        "name": "Indonesia",
        "officialName": "Republic of Indonesia",
        "continent": "Asia",
        "capital": "Jakarta",
        "population": 273523621,
        "currency": {
                        "officialName": "Indonesian rupiah",
                        "symbol": "Rp",
                        "name": "IDR"
                    },
        "areaKM": 1904569,
        "highestPoint": "Puncak Jaya",
        "highestPointMetres": 4884, 
        "olympicMedalsTotal": 37,
        "goldMedals": 8, 
        "silverMedals": 14, 
        "bronzeMedals": 15,
        "about" : "Indonesia, officially the Republic of Indonesia, is a country in Southeast Asia and Oceania between the Indian and Pacific oceans. It consists of over seventeen thousand islands, including Sumatra, Java, Sulawesi, and parts of Borneo and New Guinea.",
        "officialLanguage": "Indonesian",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/id.svg",
        "borderingCountries": "Papua New Guinea, Malaysia and Timor-Leste",
        "nationalAnimal": "Komodo dragon",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Komodo_dragon_%28Varanus_komodoensis%29.jpg/1520px-Komodo_dragon_%28Varanus_komodoensis%29.jpg",
        "googleMap": "https://goo.gl/maps/9gfPupm5bffixiFJ6",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Borobudur_Temple.jpg/1920px-Borobudur_Temple.jpg"
    },
    
    {
        "name": "Cambodia",
        "officialName": "Kingdom of Cambodia",
        "continent": "Asia",
        "capital": "Phnom Penh",
        "population": 16718971,
        "currency": {
                        "officialName": "Cambodian riel",
                        "symbol": "៛",
                        "name": "KHR"
                    },
        "areaKM": 181035,
        "highestPoint": "Mount Aôral",
        "highestPointMetres": 1813,
        "olympicMedalsTotal": 0,
        "goldMedals": 0, 
        "silverMedals": 0, 
        "bronzeMedals": 0 ,
        "about" : "Cambodia is a Southeast Asian nation whose landscape spans low-lying plains, the Mekong Delta, mountains and Gulf of Thailand coastline. Phnom Penh, its capital, is home to the art deco Central Market, glittering Royal Palace and the National Museum's historical and archaeological exhibits. In the country's northwest are the ruins of Angkor Wat, a massive stone temple complex built during the Khmer Empire.",
        "officialLanguage": "Khmer",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/kh.svg",
        "borderingCountries": "Laos, Thailand and Vietnam",
        "nationalAnimal": "Kouprey",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/4/44/Saen_Monourom_Mondul_Kiri_Cambodia_crop.jpg",
        "googleMap": "https://goo.gl/maps/nztQtFSrUXZymJaW8",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/4/44/Ankor_Wat_temple.jpg",           
                
    },
    
    {
        "name": "Taiwan",
        "officialName": "Republic of China (Taiwan)",
        "continent": "Asia",
        "capital": "Taipei",
        "population": 23503349,
        "currency": {
                        "officialName": "New Taiwan dollar",
                        "symbol": "$",
                        "name": "TWD"
                    },
        "areaKM": 36193,
        "highestPoint": "Yushan",
        "highestPointMetres": 3952,
        "olympicMedalsTotal": 36,
        "goldMedals": 7, 
        "silverMedals": 11, 
        "bronzeMedals": 1,
        "about" : "Taiwan, officially the Republic of China, is a country in East Asia. It shares maritime borders with the People's Republic of China to the northwest, Japan to the northeast, and the Philippines to the south.",
        "officialLanguage": "Chinese",
        "independent": "No",
        "unMember": "No",
        "flag": "https://flagcdn.com/tw.svg",
        "borderingCountries": "This Country does not border any Countries",
        "nationalAnimal": "Formosan black bear(unofficial)",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Formosan_Black_Bear.JPG/900px-Formosan_Black_Bear.JPG",
        "googleMap": "https://goo.gl/maps/HgMKFQjNadF3Wa6B6",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Chiang_Kai-shek_memorial_amk.jpg/2560px-Chiang_Kai-shek_memorial_amk.jpg",
        
    },
    
    {
        "name": "India",
        "officialName": "Republic of India",
        "continent": "Asia",
        "capital": "New Delhi",
        "population": 1380004385,
        "currency": {
                        "officialName": "Indian rupee",
                        "symbol": "₹",
                        "name": "INR"
                     },
        "areaKM": 3287590,
        "highestPoint": "Kangchenjunga",
        "highestPointMetres": 8586,
        "olympicMedalsTotal": 35,
        "goldMedals": 10, 
        "silverMedals": 9, 
        "bronzeMedals": 16,
        "about" : "India, officially the Republic of India, is a country in South Asia. It is the seventh-largest country by area, the second-most populous country, and the most populous democracy in the world.",
        "officialLanguage": "Hindi",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/in.svg",
        "borderingCountries": "Bangladesh, Bhutan, Myanmar(Burma), China, Nepal and Pakistan",
        "nationalAnimal": "Tiger",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/4/49/Panthera_tigris_tigris.jpg",
        "googleMap": "https://goo.gl/maps/WSk3fLwG4vtPQetp7",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Taj_Mahal_in_India_-_Kristian_Bertel.jpg/1600px-Taj_Mahal_in_India_-_Kristian_Bertel.jpg",
    },
    
    {
        "name": "Singapore",
        "officialName": "Republic of Singapore",
        "continent": "Asia",
        "capital": "Singapore",
        "population": 5685807,
        "currency": {
                        "officialName": "Singapore dollar",
                        "symbol": "$",
                        "name": "SGD"
                     },
        "areaKM": 710,
        "highestPoint": "Bukit Timah Hill",
        "highestPointMetres": 163.63,
        "olympicMedalsTotal": 5,
        "goldMedals": 1, 
        "silverMedals": 2, 
        "bronzeMedals": 2,
        "about" : "Singapore, officially the Republic of Singapore, is a sovereign island city-state in maritime Southeast Asia.",
        "officialLanguage": "Malay",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/sg.svg",
        "borderingCountries": "Malaysia and Indonesia",
        "nationalAnimal": "Lion",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Lion_d%27Afrique.jpg/1099px-Lion_d%27Afrique.jpg",
        "googleMap": "https://goo.gl/maps/QbQt9Y9b5KFzsahV6",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Marina_Bay_Sands_from_Gardens_By_The_Bay.jpg"
    },
    
    {
        "name": "Hong Kong",
        "officialName": "Hong Kong Special Administrative Region of the People's Republic of China",
        "continent": "Asia",
        "capital": "City of Victoria",
        "population": 7500700,
        "currency": {
                        "officialName": "Hong Kong dollar",
                        "symbol": "$",
                        "name": "HKD"
                     },
        "areaKM": 1104,
        "highestPoint": "Tai Mo Shan",
        "highestPointMetres": 957,
        "olympicMedalsTotal": 9,
        "goldMedals": 2, 
        "silverMedals": 3, 
        "bronzeMedals": 4,
        "about" : "Hong Kong, officially the Hong Kong Special Administrative Region of the People's Republic of China, is a city and special administrative region of China on the eastern Pearl River Delta in South China.",
        "officialLanguage": "Chinese",
        "independent": "No",
        "unMember": "No",
        "flag": "https://flagcdn.com/hk.svg",
        "borderingCountries": "China",
        "nationalAnimal": "Giant Panda",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Grosser_Panda.JPG/1600px-Grosser_Panda.JPG",
        "googleMap": "https://goo.gl/maps/1sEnNmT47ffrC8MU8",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/c/c9/Tian_Tan_Buddha_001.jpg",
    },
    
    {
        "name": "Japan",
        "officialName": "Japan",
        "continent": "Asia",
        "capital": "Tokyo",
        "population": 125836021,
        "currency": {
                        "officialName": "Japanese yen",
                        "symbol": "¥",
                        "name": "JPY"
                     },
        "areaKM": 377930,
        "highestPoint": "Mount Fuji",
        "highestPointMetres": 3776,
        "olympicMedalsTotal": 497,
        "goldMedals": 169, 
        "silverMedals": 150, 
        "bronzeMedals": 178,
        "about" : "Japan is an island country in East Asia, located in the northwest Pacific Ocean. It is bordered on the west by the Sea of Japan, and extends from the Sea of Okhotsk in the north toward the East China Sea and Taiwan in the south.",
        "officialLanguage": "Japanese",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/jp.svg",
        "borderingCountries": "South Korea",
        "nationalAnimal": "Japanese macaque",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Japanese_Snow_Monkey_%28Macaque%29_Mother_Grooms_Her_Young.jpg/976px-Japanese_Snow_Monkey_%28Macaque%29_Mother_Grooms_Her_Young.jpg",
        "googleMap": "https://goo.gl/maps/NGTLSCSrA8bMrvnX9",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/080103_hakkai_fuji.jpg/1920px-080103_hakkai_fuji.jpg"
    },
    
    {
        "name": "South Korea",
        "officialName": "Republic of Korea",
        "continent": "Asia",
        "capital": "Seoul",
        "population": 51780579,
        "currency": {
                        "officialName": "South Korean won",
                        "symbol": "₩",
                        "name": "KRW"
                     },
        "areaKM": 100210,
        "highestPoint": "Hallasan",
        "highestPointMetres": 1950,
        "olympicMedalsTotal": 287,
        "goldMedals": 96, 
        "silverMedals": 91, 
        "bronzeMedals": 100,
        "about" : "South Korea, an East Asian nation on the southern half of the Korean Peninsula, shares one of the world’s most heavily militarized borders with North Korea. It’s equally known for its green, hilly countryside dotted with cherry trees and centuries-old Buddhist temples, plus its coastal fishing villages, sub-tropical islands and high-tech cities such as Seoul, the capital.",
        "officialLanguage": "Korean",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/kr.svg",
        "borderingCountries": "North Korea",
        "nationalAnimal": "The Siberian tiger",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/P.t.altaica_Tomak_Male.jpg/1599px-P.t.altaica_Tomak_Male.jpg",
        "googleMap": "https://goo.gl/maps/7ecjaJXefjAQhxjGA",
        "landmark": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/%EC%97%AD%EC%82%AC%EC%86%8D%EC%9C%BC%EB%A1%9C.jpg/1600px-%EC%97%AD%EC%82%AC%EC%86%8D%EC%9C%BC%EB%A1%9C.jpg",
    },
    
    {
        "name": "Australia",
        "officialName": "Commonwealth of Australia",
        "continent": "Oceania",
        "capital": "Canberra",
        "population": 25687041,
        "currency": {
                        "officialName": "Australian dollar",
                        "symbol": "$",
                        "name": "AUD"
                     },
        "areaKM": 7692024,
        "highestPoint": "Mount Kosciuszko",
        "highestPointMetres": 2228,
        "olympicMedalsTotal":547,
        "goldMedals": 164, 
        "silverMedals": 173, 
        "bronzeMedals": 210,
        "about" : "Australia, officially the Commonwealth of Australia, is a sovereign country comprising the mainland of the Australian continent, the island of Tasmania, and numerous smaller islands. It is the largest country by area in Oceania and the world's sixth-largest country.",
        "officialLanguage": "English",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/au.svg",
        "borderingCountries": "This Country does not border any Countries",
        "nationalAnimal": "Red Kangaroo",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/f/f1/Red_kangaroo_-_melbourne_zoo.jpg",
        "googleMap": "https://goo.gl/maps/DcjaDa7UbhnZTndH6",
        "landmark": "https://3m4r5618el913vtfz3jffby9-wpengine.netdna-ssl.com/wp-content/uploads/Sydney-Opera-House-1024x603.jpg"
    },
    
    {
        "name": "Fiji",
        "officialName": "Republic of Fiji",
        "continent": "Oceania",
        "capital": "Suva",
        "population": 896444,
        "currency": {
                        "officialName": "Fijian dollar",
                        "symbol": "$",
                        "name": "FJD"
                     },
        "areaKM": 18272,
        "highestPoint":  "Tomanivi",
        "highestPointMetres": 1324,
        "totalMedalcount": 3,               
        "goldMedals": 2, 
        "silverMedals": 0, 
        "bronzeMedals": 1,
        "about" : "Fiji, a country in the South Pacific, is an archipelago of more than 300 islands. It's famed for rugged landscapes, palm-lined beaches and coral reefs with clear lagoons. Its major islands, Viti Levu and Vanua Levu, contain most of the population. Viti Levu is home to the capital, Suva, a port city with British colonial architecture. The Fiji Museum, in the Victorian-era Thurston Gardens, has ethnographic exhibits.",
        "officialLanguage": "English, Fijian, Hindi",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/fj.svg",
        "borderingCountries": "This Country does not border any Countries",
        "nationalAnimal": "Collared Lory",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Collared_Lories_taveuni_june2008.JPG/1496px-Collared_Lories_taveuni_june2008.JPG",
        "googleMap": "https://goo.gl/maps/r9fhDqoLZdg1zmE99",
        "landmark": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/14/a6/c3/72/20180915-124141-largejpg.jpg?w=1000&h=-1&s=1"
    },
    
    {
        "name": "Samoa",
        "officialName": "Independent State of Samoa",
        "continent": "Oceania",
        "capital": "Apia",
        "population": 198410,
        "currency": {
                        "officialName": "Samoan tālā",
                        "symbol": "T",
                        "name": "WST"
                     },
        "areaKM": 2842,
        "highestPoint": "Mount Silisili",
        "highestPointMetres": 1858,     
        "olympicMedalsTotal": 1,
        "goldMedals": 0, 
        "silverMedal": 1, 
        "bronzeMedals": 0,
        "about" : "Samoa, officially the Independent State of Samoa and until 1997 known as Western Samoa, is a Polynesian island country consisting of two main islands, two smaller, inhabited islands, and several smaller, uninhabited islands, including the Aleipata Islands.",
        "officialLanguage": "Samoan, English",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/ws.svg",
        "borderingCountries": "This Country does not border any Countries",
        "nationalAnimal": "Humpback whale",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/6/61/Humpback_Whale_underwater_shot.jpg",
        "googleMap": "https://goo.gl/maps/CFC9fEFP9cfkYUBF9",
        "landmark": "https://www.wondermondo.com/wp-content/uploads/2017/10/ToSua.jpg"
    },
    
    {
        "name": "Tonga",
        "officialName": "Kingdom of Tonga",
        "continent": "Oceania",
        "capital": "Nuku'alofa",
        "population": 105697,
        "currency": {
                        "officialName": "Tongan paʻanga",
                        "symbol": "T$",
                        "name": "TOP"
                     },
        "areaKM": 747,
        "highestPointMetres": 1033,
        "highestPoint": "Kao Island",
        "olympicMedalsTotal": 1,
        "goldMedals": 0, 
        "silverMedals":0,
        "bronzeMedals":1,
        "about" : "Tonga is a Polynesian kingdom of more than 170 South Pacific islands, many uninhabited, most lined in white beaches and coral reefs and covered with tropical rainforest. The main island, Tongatapu, is protected by lagoons and limestone cliffs. It’s home to the rural capital of Nuku'alofa, as well as beach resorts, plantations and the Ha'amonga ʻa Maui, a monumental coral gate from the 1200s.",
        "officialLanguage": "Tongan",
        "independent": "Yes",
        "unMember": "Yes",
        "flag": "https://flagcdn.com/to.svg",
        "borderingCountries": "This Country does not border any Countries",
        "nationalAnimal": "Radiated tortoise",
        "animalPhoto": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/TuiMalila.jpg/1920px-TuiMalila.jpg",
        "googleMap": "https://goo.gl/maps/p5YALBY2QdEzswRo7",
        "landmark": "https://www.wondermondo.com/wp-content/uploads/2017/10/RoyalPalaceTonga-640x446.jpg?ezimgfmt=ng:webp/ngcb20"
    }, 
]);